/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JOptionPane;
import model.Citizen;
import service.CitizenInterface;

/**
 *
 * @author Admin
 */
public class CitizeRegistry extends javax.swing.JFrame {

    /**
     * Creates new form CitizeRegistry
     */
    public CitizeRegistry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        citizenIdTxt = new javax.swing.JTextField();
        fullnamesTxt = new javax.swing.JTextField();
        phoneNumberTxt = new javax.swing.JTextField();
        registerBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        prinfDataBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addVaccineBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Citizen Registry");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(214, 33, 150, 39);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Citizen Id:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(91, 103, 80, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("FullNames:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(89, 166, 80, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Phone number:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(63, 211, 107, 40);
        jPanel1.add(citizenIdTxt);
        citizenIdTxt.setBounds(191, 110, 219, 26);
        jPanel1.add(fullnamesTxt);
        fullnamesTxt.setBounds(191, 166, 219, 26);
        jPanel1.add(phoneNumberTxt);
        phoneNumberTxt.setBounds(191, 221, 219, 26);

        registerBtn.setBackground(new java.awt.Color(0, 102, 102));
        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });
        jPanel1.add(registerBtn);
        registerBtn.setBounds(205, 286, 100, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel5.setText("Do you wish to vaccine Citizen?");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 380, 290, 22);

        prinfDataBtn.setBackground(new java.awt.Color(204, 255, 204));
        prinfDataBtn.setText("Yes");
        prinfDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prinfDataBtnActionPerformed(evt);
            }
        });
        jPanel1.add(prinfDataBtn);
        prinfDataBtn.setBounds(321, 423, 70, 40);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel6.setText("Do you wish to Display Inforamtion?");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(14, 427, 300, 22);

        addVaccineBtn.setBackground(new java.awt.Color(204, 255, 204));
        addVaccineBtn.setText("Yes");
        addVaccineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccineBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addVaccineBtn);
        addVaccineBtn.setBounds(320, 369, 70, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Desktop\\_DSC0143ANP.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 0, 620, 570);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 630, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
       //valifation
       
       if(citizenIdTxt.getText().isEmpty() || fullnamesTxt.getText().isEmpty() || phoneNumberTxt.getText().isEmpty()){
           JOptionPane.showMessageDialog(this, "Kindly provide all inforamtion","Empty Field!" , JOptionPane.ERROR_MESSAGE);
       }
       else{
           try{
               Registry registry = LocateRegistry.getRegistry("127.0.0.1",7000);
               CitizenInterface intrf =(CitizenInterface)registry.lookup("citizen");
               Citizen citizen = new Citizen();
               citizen.setCitizen_id(citizenIdTxt.getText());
               citizen.setFullnames(fullnamesTxt.getText());
               citizen.setPhone_number(phoneNumberTxt.getText());
               citizen.setIs_vaccinate(false);
               String feedback = intrf.registerCitizen(citizen);
               JOptionPane.showMessageDialog(this, feedback,"Successful!" , JOptionPane.INFORMATION_MESSAGE);

           } catch(Exception ex){
               ex.printStackTrace();
               
           }
           

       }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void addVaccineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccineBtnActionPerformed

      VaccineRegistry vaccineRegistry = new VaccineRegistry();
      vaccineRegistry.setVisible(true);
      dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_addVaccineBtnActionPerformed

    private void prinfDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prinfDataBtnActionPerformed

Data_Printing data_Printing = new Data_Printing();
data_Printing.setVisible(true);
dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_prinfDataBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitizeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitizeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitizeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitizeRegistry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitizeRegistry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccineBtn;
    private javax.swing.JTextField citizenIdTxt;
    private javax.swing.JTextField fullnamesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JButton prinfDataBtn;
    private javax.swing.JButton registerBtn;
    // End of variables declaration//GEN-END:variables
}
